import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Pause, Play, SkipForward, Square, Clock3, ShieldCheck, ChevronDown } from 'lucide-react';
import type { Assessment, Cursor, Draft, Profile, Session, Step } from './model';
import { uuid, formatTime } from './model';
import { exercises, getSteps, phaseNames, phaseOf, topics } from './content';
import { AudioPanel, BreathTool, NoteSelect, ReadingTool } from './Tools';
import { NumberField, ChoiceField } from './components';
import { noteName, meanAbs } from './music';

function DurationTest({label,values,onChange}:{label:string;values:number[]|undefined;onChange:(v:number[])=>void}){const [start,setStart]=useState<number|null>(null),[elapsed,setElapsed]=useState(0);useEffect(()=>{if(start===null)return;const id=setInterval(()=>setElapsed((performance.now()-start)/1000),100);const hide=()=>{if(document.hidden){setStart(null);setElapsed(0);}};document.addEventListener('visibilitychange',hide);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',hide);};},[start]);return <div className="duration-test"><strong>{label}</strong><div className="button-row"><button className={`btn ${start===null?'secondary':'danger'}`} onClick={()=>{if(start===null){setElapsed(0);setStart(performance.now());}else {const n=Math.round((performance.now()-start)/100)/10;onChange([...(values||[]).slice(-1),n]);setStart(null);}}}>{start===null?<Play size={15}/>:<Square size={15}/>} {start===null?'Denemeyi başlat':`Bitir · ${elapsed.toFixed(1)} sn`}</button><span>{values?.map(n=>`${n.toFixed(1)} sn`).join(' / ')||'İki deneme bekleniyor'}</span></div><div className="form-grid">{[0,1].map(i=><NumberField key={i} label={`${i+1}. deneme (sn)`} value={values?.[i]} step={.1} max={120} onChange={v=>{const next=[...(values||[])];if(v===undefined)next.splice(i,1);else next[i]=v;onChange(next.filter(Number.isFinite));}}/>)}</div></div>;}

function TestFields({step,a,setA,profile,cursor}:{step:Step;a:Assessment;setA:(a:Assessment)=>void;profile:Profile;cursor:Cursor}){
 const put=(patch:Partial<Assessment>)=>setA({...a,...patch});
 if(step.exercise==='CAL')return <><div className="notice">Dahili referans: A4 = 440 Hz, A2 = 110 Hz. Aşağıdaki piyano ve mikrofonla araçları deneyebilirsin.</div><ChoiceField label="Referans seslerini dinledim ve araçları kontrol ettim" value={a.calibration} onChange={v=>put({calibration:v})}/></>;
 if(step.exercise==='T1')return <NoteSelect label="Konuşmada en sık kaldığın nota" value={a.speech} empty onChange={v=>put({speech:v})}/>;
 if(step.exercise==='T2')return <div className="form-grid"><NoteSelect label="En pes rahat nota" value={a.low} empty onChange={v=>put({low:v})}/><NoteSelect label="P · geçiş notası (emin değilsen boş bırak)" value={a.transition} empty onChange={v=>put({transition:v})}/><NoteSelect label="Rahat üst / falsetto nota" value={a.high} empty onChange={v=>put({high:v})}/></div>;
 if(step.exercise==='T3')return <div className="test-trials"><div className="notice">Her hedef için üç deneme. Hedef notayı tuner'dan seç. Rahat aralığını değiştirmek gerekirse önce seansı kaydedip ayarlara dön.</div>{step.notes?.map(n=>{const values=(a.pitch||[]).filter(t=>t.note===n);return <div className="trial-row" key={n}><strong>{noteName(n)}</strong><span>{values.length}/3</span><span>{values.length?`${meanAbs(values.map(t=>t.cents))?.toFixed(1)} cent`:'Ölçülmedi'}</span><button className="text-btn" onClick={()=>put({pitch:(a.pitch||[]).filter(t=>t.note!==n)})}>Yeniden al</button></div>;})}</div>;
 if(step.exercise==='T4')return <>{(['ah','sss','zzz'] as const).map(k=><DurationTest key={k} label={k} values={a[k]} onChange={v=>put({[k]:v})}/>)}<p className="muted">sss için perde ölçümü kullanılmaz. Kronometreyi sesin başlangıç/bitişinde kontrol et.</p></>;
 if(step.exercise==='T5')return <div className="form-grid"><NumberField label="Yutulan / hatalı kelime" value={a.errors} onChange={v=>put({errors:v,textVersion:profile.textVersion})}/><NumberField label="3 tekerlemede S/Ş sayısı" value={a.leakage} onChange={v=>put({leakage:v,textVersion:profile.textVersion})}/><NumberField label="Kelime sonu yutma" value={a.endings} onChange={v=>put({endings:v,textVersion:profile.textVersion})}/></div>;
 if(step.exercise==='GATE')return <div className="form-grid">
  {cursor.week===3&&<><NumberField label="Humming süresi (sn)" value={a.humming} max={120} step={.1} onChange={v=>put({humming:v})}/><ChoiceField label="Humming kararlı mıydı?" value={a.stable} onChange={v=>put({stable:v})}/></>}
  {cursor.week===6&&<><p className="span-all muted">Beşli sıçramada ikinci notaya giriş için beş işaretli cent değerini kaydet. Arpej/piyano ve tuner aşağıda.</p>{Array.from({length:5},(_,i)=><NumberField key={i} label={`Sıçrama ${i+1} · cent`} value={a.jumps?.[i]} min={-1200} max={1200} onChange={v=>{const jumps=[...(a.jumps||[])];if(v===undefined)jumps.splice(i,1);else jumps[i]=v;put({jumps});}}/>)}</>}
  {cursor.week===9&&<NumberField label="5 denemede çatlamasız geçiş" value={a.crossings} max={5} onChange={v=>put({crossings:v})}/>}
  {cursor.week===12&&<><ChoiceField label="20 dk seans sonunda gıcık, yanma, öksürük veya kısıklık yok mu?" value={a.symptomFree} onChange={v=>put({symptomFree:v})}/><ChoiceField label="Referans melodiye göre bir kıta ±35 cent içinde mi?" value={a.song} onChange={v=>put({song:v})}/></>}
 </div>;
 return null;
}
function hasRequired(step:Step,a:Assessment):boolean {
 switch(step.exercise){case 'CAL':return a.calibration===true;case 'T1':return a.speech!==undefined;case 'T2':return a.low!==undefined&&a.high!==undefined&&a.low<=a.high;case 'T3':return !!step.notes?.length&&step.notes.every(n=>(a.pitch||[]).filter(t=>t.note===n).length>=3);case 'T4':return [a.ah,a.sss,a.zzz].every(x=>x?.length===2&&x.every(n=>n>0));case 'T5':return a.errors!==undefined&&a.leakage!==undefined&&a.endings!==undefined;default:return true;}
}

export function SessionView({profile,cursor,initial,onDraft,onFinish,onClose}:{profile:Profile;cursor:Cursor;initial:Draft|null;onDraft:(d:Draft)=>void;onFinish:(s:Session)=>Promise<void>;onClose:()=>void}){
 const steps=getSteps(cursor,profile),[draft,setDraft]=useState<Draft>(initial||{id:uuid(),cursor,step:0,completed:[],skipped:[],elapsed:0,totalSeconds:0,assessment:{},interrupted:false}),[ready,setReady]=useState(!!initial),[running,setRunning]=useState(false),[summary,setSummary]=useState(false),[throat,setThroat]=useState<number|undefined>(),[note,setNote]=useState(''),[stopped,setStopped]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const saveRef=useRef(onDraft);saveRef.current=onDraft;const current=steps[draft.step],exercise=current?exercises[current.exercise]:null;
 useEffect(()=>{saveRef.current(draft);},[draft]);
 useEffect(()=>{if(!running)return;let last=performance.now();const timer=setInterval(()=>{const now=performance.now(),delta=(now-last)/1000;last=now;setDraft(d=>({...d,elapsed:d.elapsed+delta,totalSeconds:d.totalSeconds+delta}));},500);return()=>clearInterval(timer);},[running]);
 useEffect(()=>{const hide=()=>{if(document.hidden){setRunning(false);setDraft(d=>({...d,interrupted:true}));}};document.addEventListener('visibilitychange',hide);let lock:WakeLockSentinel|undefined;if('wakeLock'in navigator)navigator.wakeLock.request('screen').then(l=>{lock=l;}).catch(()=>{});return()=>{document.removeEventListener('visibilitychange',hide);void lock?.release();};},[]);
 const move=(skip:boolean)=>{if(!current)return;if(!skip&&!hasRequired(current,draft.assessment)){setError('Bu testin ölçümleri henüz tamamlanmadı. Eksik alanları doldur veya adımı atla.');return;}setError('');setRunning(false);setDraft(d=>({...d,step:Math.min(d.step+1,steps.length),elapsed:0,completed:skip?d.completed:[...d.completed,current.id],skipped:skip?[...d.skipped,current.id]:d.skipped}));if(draft.step+1>=steps.length)setSummary(true);};
 const finish=async()=>{if(throat===undefined){setError('Seans sonu boğaz hissini 0–10 arasında kaydet.');return;}setBusy(true);setError('');try{const required=steps.filter(s=>!exercises[s.exercise].optional);await onFinish({id:draft.id,cursor,date:new Date().toISOString(),seconds:Math.round(draft.totalSeconds),throat,note,completed:draft.completed,skipped:draft.skipped,assessment:draft.assessment,interrupted:draft.interrupted,status:stopped?'stopped':required.every(s=>draft.completed.includes(s.id))?'complete':'partial'});}catch(e){setError((e as Error).message);setBusy(false);}};
 if(!ready)return <div className="session-intro card"><span className="tile-icon mint"><ShieldCheck/></span><span className="eyebrow">KÜÇÜK BİR KONTROL</span><h1>Bugün sesin nasıl?</h1><p>Ağrı, yanma, kısıklık veya ses kaybı hissediyorsan çalışmayı bugün durdur. Rahat hissediyorsan başlayalım.</p><div className="button-row center"><button className="btn primary" onClick={()=>{setReady(true);setRunning(true);}}>Rahat hissediyorum <ArrowRight size={17}/></button><button className="btn secondary" onClick={()=>{setStopped(true);setReady(true);setSummary(true);}}>Bugün dinleneceğim</button></div><button className="text-btn" onClick={onClose}>Geri dön</button></div>;
 if(summary||!current)return <div className="card session-summary"><span className="tile-icon lavender"><Check/></span><span className="eyebrow">KENDİNE AYIRDIĞIN ZAMAN</span><h1>{stopped?'Bugün dinlenmeye alan aç.':'Çalışmanı kaydedelim.'}</h1><div className="summary-stats"><div><strong>{formatTime(draft.totalSeconds)}</strong><span>aktif süre</span></div><div><strong>{draft.completed.length}/{steps.length}</strong><span>tamamlanan adım</span></div></div><NumberField label="Boğaz hissi · 0 rahat, 10 belirgin rahatsızlık" value={throat} max={10} onChange={setThroat}/><label className="field">Bugünden bir not<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Nerede rahat hissettin? Hangi egzersiz zorladı?" rows={4}/></label>{draft.skipped.length>0&&<p className="notice">Atlanan zorunlu adımlar tamamlanmış sayılmaz. Kısmi seans kaydedilir ve program bu günde kalır.</p>}{error&&<p className="notice error" role="alert">{error}</p>}<button className="btn primary" disabled={busy} onClick={finish}>{busy?'Kaydediliyor…':'Seansı kaydet'} <Check size={17}/></button></div>;
 const isTest=exercise?.category==='Ölçüm',needsReading=current.exercise.startsWith('D')||['T1','T5'].includes(current.exercise);
 return <div className="session-view"><div className="session-top"><button className="text-btn" onClick={()=>{setRunning(false);onClose();}}><ArrowLeft size={18}/> Kaydet ve çık</button><span>{phaseNames[phaseOf(cursor.week)]} · {draft.step+1}/{steps.length}</span><button className="text-btn danger-text" onClick={()=>{setRunning(false);setStopped(true);setSummary(true);}}>Seansı bitir</button></div><div className="step-progress">{steps.map((s,i)=><span key={s.id} className={i<draft.step?'done':i===draft.step?'active':''}/>)}</div>
 <div className="session-grid"><aside className="card instruction-card"><span className="eyebrow">{exercise?.category} · {exercise?.id}</span><h1>{exercise?.name}</h1><p>{exercise?.description}</p><ol>{exercise?.steps.map((t,i)=><li key={i}>{t}</li>)}</ol>{current.detail&&<div className="notice">{current.detail}</div>}<div className="tip"><ShieldCheck size={18}/><p>{exercise?.tip}</p></div><small className="muted">Program kaynağı · PDF s. {exercise?.page}</small><div className="timer"><Clock3 size={20}/><strong>{formatTime(draft.elapsed)}</strong><span>/ yaklaşık {formatTime(current.seconds)}</span></div><button className="btn secondary full" onClick={()=>setRunning(v=>!v)}>{running?<Pause size={17}/>:<Play size={17}/>} {running?'Süreyi duraklat':'Süreyi başlat'}</button>{draft.interrupted&&<p className="muted">Kesinti kaydedildi. Hazır olduğunda devam et.</p>}</aside>
 <div className="session-work card">{current.blocked?<div className="notice error">{current.blocked}</div>:<>
 {isTest&&<TestFields step={current} a={draft.assessment} setA={a=>setDraft(d=>({...d,assessment:a}))} profile={profile} cursor={cursor}/>}
 {current.exercise==='D9'&&<div className="notice"><strong>Bugünün konusu</strong><p>{topics[Math.floor((cursor.week*5+cursor.day)/2)%topics.length]}</p><p>3 dk konuş; ardından kaydı dinleyip aksayan üç yeri seans notuna yaz.</p></div>}
 {needsReading&&<details open={current.exercise.startsWith('D')} className="reading-details"><summary>Okuma metni ve tekerlemeler <ChevronDown size={16}/></summary><ReadingTool profile={profile}/></details>}
 {current.exercise==='E10'?<BreathTool/>:<AudioPanel key={current.id} profile={profile} notes={current.notes} exercise={current.exercise} sessionId={draft.id} hidden={current.hidden} onTrial={current.exercise==='T3'?t=>setDraft(d=>({...d,assessment:{...d.assessment,pitch:[...(d.assessment.pitch||[]),t]}})):undefined} onSpeech={current.exercise==='T1'?n=>setDraft(d=>({...d,assessment:{...d.assessment,speech:n}})):undefined}/>}
 </>}{error&&<p role="alert" className="notice error">{error}</p>}<div className="session-actions"><button className="btn subtle" onClick={()=>move(true)}><SkipForward size={16}/> Adımı atla</button><button className="btn primary" disabled={!!current.blocked} onClick={()=>move(false)}>Tamamladım <ArrowRight size={17}/></button></div></div></div></div>;
}
