import { useEffect, useRef, useState } from 'react';
import { Mic, MicOff, Play, Square, Volume2, Music2, Wind, FileText, Radio, RotateCcw, Eye, EyeOff, Check, Download, Trash2, Flag } from 'lucide-react';
import { AudioEngine } from './audio';
import type { AudioFrame } from './audio';
import type { Profile, Trial, Recording } from './model';
import { uuid, formatTime } from './model';
import { centsFrom, hzMidi, median, midiHz, noteName, noteTr } from './music';
import { allRecordings, saveRecording, deleteRecording, download } from './storage';
import { Empty, NumberField } from './components';

export function NoteSelect({label,value,onChange,empty=false}:{label:string;value:number|undefined|null;onChange:(v:number|undefined)=>void;empty?:boolean}){return <label className="field">{label}<select value={value??''} onChange={e=>onChange(e.target.value===''?undefined:Number(e.target.value))}>{empty&&<option value="">Henüz belirlenmedi</option>}{Array.from({length:49},(_,i)=>i+33).map(n=><option key={n} value={n}>{noteName(n)} · {noteTr(n)}</option>)}</select></label>;}

export function AudioPanel({profile,notes,exercise,sessionId,onTrial,onSpeech,hidden=false}:{profile:Profile;notes?:number[];exercise?:string;sessionId?:string;onTrial?:(t:Trial)=>void;onSpeech?:(n:number)=>void;hidden?:boolean}){
 const engine=useRef(new AudioEngine());const [mic,setMic]=useState(false),[frame,setFrame]=useState<AudioFrame|null>(null),[history,setHistory]=useState<(number|null)[]>([]),[error,setError]=useState(''),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[message,setMessage]=useState(''),[target,setTarget]=useState(notes?.[0]??48),[phase,setPhase]=useState(''),[last,setLast]=useState<number|null>(null),[revealed,setRevealed]=useState(!hidden),[manual,setManual]=useState<number|undefined>(),[sequence,setSequence]=useState((notes?.length?notes:[48,50,52,55,52,50,48]).join(','));
 const micRef=useRef(false),recordRef=useRef(false),trial=useRef<{target:number;start:number|null;values:number[];deadline:number}|null>(null),speech=useRef<{until:number;values:number[]}|null>(null),timers=useRef<ReturnType<typeof setTimeout>[]>([]),saving=useRef(false),alive=useRef(true);
 const trialCallback=useRef(onTrial);trialCallback.current=onTrial;const speechCallback=useRef(onSpeech);speechCallback.current=onSpeech;
 const cancel=()=>{timers.current.forEach(clearTimeout);timers.current=[];trial.current=null;speech.current=null;engine.current.stopTone();setPhase('');};
 const endRecord=async()=>{if(saving.current)return;saving.current=true;try{const data=await engine.current.stopRecording();recordRef.current=false;if(alive.current)setRecording(false);if(data&&data.blob.size){await saveRecording({id:uuid(),date:new Date().toISOString(),title:`${exercise||'Serbest çalışma'} · ${new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}`,exercise,sessionId,...data,markers:[]});if(alive.current)setMessage('Kayıt arşivine eklendi.');}}catch(e){if(alive.current)setError(String(e));}finally{saving.current=false;}};
 useEffect(()=>{alive.current=true;const visibility=()=>{if(document.hidden){cancel();if(recordRef.current)void endRecord();engine.current.stopMic();micRef.current=false;setMic(false);setMessage('Çalışma kesintiye uğradı. Dönünce mikrofonu yeniden aç.');}};document.addEventListener('visibilitychange',visibility);return()=>{alive.current=false;document.removeEventListener('visibilitychange',visibility);timers.current.forEach(clearTimeout);void(async()=>{if(recordRef.current)await endRecord();await engine.current.close();})();};},[]);
 useEffect(()=>{if(!recording)return;const id=setInterval(()=>setSeconds((performance.now()-engine.current.recordStarted)/1000),200);return()=>clearInterval(id);},[recording]);
 const receive=(f:AudioFrame)=>{
  setFrame(f);setHistory(h=>[...h.slice(-59),f.frequency?hzMidi(f.frequency):null]);
  const t=trial.current;
  if(t){if(f.time>t.deadline){trial.current=null;setPhase('Ses ölçülemedi. Yeniden dene.');return;}if(f.frequency&&f.confidence>.85){if(t.start===null)t.start=f.time;if(f.time-t.start<=500)t.values.push(centsFrom(f.frequency,t.target));}
   if(t.start!==null&&f.time-t.start>=500){trial.current=null;const result=t.values.length>=4?median(t.values):null;if(result===null){setPhase('Yeterli temiz ses yok. Yeniden dene.');return;}setLast(result);setPhase('Giriş ölçüldü');trialCallback.current?.({note:t.target,cents:result,at:new Date().toISOString(),method:'microphone'});}}
  if(speech.current){if(f.frequency)speech.current.values.push(Math.round(hzMidi(f.frequency)));if(f.time>=speech.current.until){const a=speech.current.values;speech.current=null;const count=new Map<number,number>();a.forEach(n=>count.set(n,(count.get(n)||0)+1));const best=[...count.entries()].sort((a,b)=>b[1]-a[1])[0];if(best&&a.length>=20){speechCallback.current?.(best[0]);setPhase(`Konuşma perdesi: ${noteName(best[0])}`);}else setPhase('Konuşma için yeterli ses ölçülemedi.');}}
 };
 const openMic=async()=>{if(micRef.current)return true;setError('');try{await engine.current.microphone(receive);micRef.current=true;setMic(true);return true;}catch(e){setError((e as Error).message);return false;}};
 const play=async(ns:number[])=>{setError('');try{await engine.current.play(ns);}catch(e){setError((e as Error).message);}};
 const beginTrial=async()=>{cancel();setLast(null);if(!await openMic())return;await engine.current.play([target],1,0);setPhase('Notayı dinle');timers.current.push(setTimeout(()=>setPhase('2 saniye bekle'),1000));timers.current.push(setTimeout(()=>{setPhase('Şimdi “nu” ile söyle');trial.current={target,start:null,values:[],deadline:performance.now()+7000};},3000));};
 const toggleRecord=async()=>{if(recording){await endRecord();return;}if(!await openMic())return;try{engine.current.startRecording();recordRef.current=true;setRecording(true);setSeconds(0);setMessage('');}catch(e){setError((e as Error).message);}};
 const detected=frame?.frequency?Math.round(hzMidi(frame.frequency)):null,cent=frame?.frequency?centsFrom(frame.frequency,target):null;
 const pts=history.map((v,i)=>v===null?null:`${i/59*500},${90-Math.max(-12,Math.min(12,v-target))*5}`).filter(Boolean).join(' ');
 return <div className="audio-panel">
  <div className="tuner"><div className="tuner-top"><span className="eyebrow">{mic?'CANLI TUNER':'SES PUSULAN'}</span><span className={`status-dot ${mic?'live':''}`}>{mic?'Mikrofon açık':'Mikrofon kapalı'}</span></div>
   <div className="tuner-reading"><span>{revealed?(detected===null?'—':noteName(detected)):'?'}</span><div>{revealed&&frame?.frequency?`${frame.frequency.toFixed(1)} Hz`:'Rahat bir sesle başla'}<small>{!revealed?'Önce dinle, sonra kontrol et':cent===null?'Temiz ses bekleniyor':Math.abs(cent)<15?'Hedefin yakınındasın':cent>0?'Hedefin üstündesin':'Hedefin altındasın'}</small></div></div>
   <div className="cent-scale"><span>−50</span><span>HEDEF · {noteName(target)}</span><span>+50</span><i style={{left:`${50+Math.max(-50,Math.min(50,cent??0))}%`,opacity:cent===null||!revealed?0:1}}/></div>
   <svg className="pitch-graph" viewBox="0 0 500 150" aria-label="Perde çizgisi"><line x1="0" x2="500" y1="90" y2="90" stroke="currentColor" strokeDasharray="4 6" opacity=".2"/>{revealed&&<polyline points={pts} fill="none" stroke="currentColor" strokeWidth="2.5"/>}</svg>
   <div className="tuner-bottom"><span>{revealed&&cent!==null?`${cent>0?'+':''}${cent.toFixed(0)} cent`:'Sesini zorlamadan söyle'}</span><span>{frame&&frame.rms>.6?'Giriş çok yüksek':mic&&frame&&frame.rms<.008?'Sessiz / düşük giriş':''}</span></div>
  </div>
  <div className="button-row"><button className={mic?'btn secondary':'btn primary'} onClick={async()=>{if(mic){cancel();if(recording)await endRecord();engine.current.stopMic();setMic(false);micRef.current=false;setFrame(null);}else await openMic();}}>{mic?<MicOff size={17}/>:<Mic size={17}/>} {mic?'Mikrofonu kapat':'Mikrofonu aç'}</button><button className={`btn ${recording?'danger':'secondary'}`} onClick={toggleRecord}>{recording?<Square size={15}/>:<Radio size={17}/>} {recording?`Kaydı bitir · ${formatTime(seconds)}`:'Ses kaydı al'}</button>{hidden&&<button className="btn subtle" onClick={()=>setRevealed(v=>!v)}>{revealed?<EyeOff size={16}/>:<Eye size={16}/>} {revealed?'Gizle':'Sonucu göster'}</button>}</div>
  {error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice success">{message}</p>}
  <div className="piano-controls"><NoteSelect label="Hedef nota" value={target} onChange={n=>n!==undefined&&setTarget(n)}/><button className="btn secondary" onClick={()=>play([target])}><Volume2 size={17}/> Dinle · {midiHz(target).toFixed(1)} Hz</button></div>
  <div className="piano" aria-label="Piyano">{Array.from({length:13},(_,i)=>Math.max(33,Math.min(69,profile.low))+i).map(n=><button key={n} className={`${[1,3,6,8,10].includes(n%12)?'black-key':''} ${n===target?'selected-key':''}`} onClick={()=>{setTarget(n);void play([n]);}}><span>{noteTr(n)}</span><small>{noteName(n)}</small></button>)}</div>
  <div className="button-row">{notes?.length&&<button className="btn secondary" onClick={()=>{const ns=hidden?[...notes].sort(()=>Math.random()-.5):notes;setRevealed(!hidden);void play(ns);}}><Music2 size={17}/> {hidden?'Rastgele diziyi dinle':'Nota dizisini dinle'}</button>}<button className="btn secondary" onClick={()=>play([target,target+4,target+7,target+4,target])}><Play size={15}/> Arpej dinle</button></div>
  <div className="measure-box"><h3>İlk girişini ölç</h3><p>1 sn dinle → 2 sn bekle → “nu” ile söyle. İlk 0,5 sn değerlendirilir.</p><button className="btn primary" onClick={beginTrial}><Play size={16}/> Denemeyi başlat</button><span className="trial-result" aria-live="polite">{phase}{last!==null&&` · ${last>0?'+':''}${last.toFixed(1)} cent`}</span>
   {onTrial&&<details><summary>Harici tuner sonucunu elle gir</summary><div className="button-row"><NumberField label="İşaretli cent" value={manual} min={-1200} max={1200} onChange={setManual}/><button className="btn secondary" disabled={manual===undefined} onClick={()=>{if(manual!==undefined){onTrial({note:target,cents:manual,at:new Date().toISOString(),method:'manual'});setManual(undefined);setMessage('Elle ölçüm eklendi.');}}}><Check size={16}/> Ekle</button></div></details>}
  </div>
  {onSpeech&&<button className="btn secondary" onClick={async()=>{cancel();if(await openMic()){speech.current={until:performance.now()+30000,values:[]};setPhase('30 saniye doğal sesinle oku…');}}}>30 sn konuşma perdesini ölç</button>}
  {(exercise==='E11'||!exercise)&&<details><summary>Kendi melodini çal</summary><label className="field">Nota numaraları (C3=48, D3=50, E3=52)<input value={sequence} onChange={e=>setSequence(e.target.value)}/></label><button className="btn secondary" onClick={()=>{const ns=sequence.split(',').map(Number);if(ns.length>64||ns.some(n=>!Number.isInteger(n)||n<33||n>81)){setError('33–81 arasında, virgülle ayrılmış en fazla 64 nota gir.');return;}void play(ns);}}><Play size={16}/> Melodiyi çal</button></details>}
 </div>;
}

export function BreathTool(){const [running,setRunning]=useState(false),[time,setTime]=useState(0);useEffect(()=>{if(!running)return;const start=performance.now()-time*1000;const id=setInterval(()=>setTime((performance.now()-start)/1000),100);return()=>clearInterval(id);},[running]);const t=Math.floor(time)%24,label=t<4?'Nefes al':t<20?'Yavaşça ver · sss':'Dinlen';return <div className="breath-tool"><div className={`breath-circle ${running&&t<4?'inhale':''}`}><Wind size={32}/><strong>{running?label:'Sakin bir başlangıç'}</strong><span>{running?`${t<4?4-t:t<20?20-t:24-t} sn`:'4 sn al · 16 sn ver · 4 sn ara'}</span></div><p>Rahat süreyi aşma. Baş dönmesi veya rahatsızlıkta dur.</p><div className="button-row center"><button className="btn primary" onClick={()=>setRunning(v=>!v)}>{running?'Duraklat':'Başla'}</button><button className="btn secondary" onClick={()=>{setRunning(false);setTime(0);}}><RotateCcw size={16}/> Sıfırla</button></div><small>{Math.floor(time/24)} döngü tamamlandı</small></div>;}

export function ReadingTool({profile}:{profile:Profile}){const [tab,setTab]=useState('reading'),[marks,setMarks]=useState<string[]>([]);return <div><div className="segmented"><button className={tab==='reading'?'active':''} onClick={()=>setTab('reading')}>Okuma metni</button><button className={tab==='twisters'?'active':''} onClick={()=>setTab('twisters')}>Tekerlemeler</button></div><p className="muted">Vurgulamak veya zorlandığın yeri işaretlemek için kelimeye dokun.</p><div className="reading-text">{(tab==='reading'?profile.reading:profile.tongueTwisters.join('\n\n')).split(/(\s+)/).map((word,i)=>/^\s+$/.test(word)?word:<button key={i} className={marks.includes(`${tab}-${i}`)?'marked':''} onClick={()=>setMarks(m=>m.includes(`${tab}-${i}`)?m.filter(x=>x!==`${tab}-${i}`):[...m,`${tab}-${i}`])}>{word}</button>)}</div><p className="muted">{marks.length} işaret · bu alıştırmadaki işaretler geçicidir; ölçüm sonucunu testte kaydet.</p></div>;}

export function ToolsPage({profile}:{profile:Profile}){const [tab,setTab]=useState('ses');return <><div className="page-heading"><div><span className="eyebrow">KÜÇÜK ARAÇLAR, BÜYÜK DESTEK</span><h1>Çalışma masan.</h1><p>Bir notayı dinle, nefesine alan aç, sesini kaydet.</p></div></div><div className="tool-tabs">{[{id:'ses',name:'Piyano & tuner',icon:Music2},{id:'nefes',name:'Nefes',icon:Wind},{id:'metin',name:'Okuma & diksiyon',icon:FileText}].map(t=><button key={t.id} className={tab===t.id?'active':''} onClick={()=>setTab(t.id)}><t.icon size={20}/>{t.name}</button>)}</div><div className="card tool-card">{tab==='ses'?<AudioPanel profile={profile}/>:tab==='nefes'?<BreathTool/>:<ReadingTool profile={profile}/>}</div></>;}

function RecordingItem({item,onChange}:{item:Recording;onChange:()=>void}){const [url,setUrl]=useState(''),[text,setText]=useState(''),[loop,setLoop]=useState(false);const audio=useRef<HTMLAudioElement>(null);useEffect(()=>{const u=URL.createObjectURL(item.blob);setUrl(u);return()=>URL.revokeObjectURL(u);},[item.blob]);return <article className="card recording-card"><div className="recording-title"><span className="tile-icon lavender"><Radio size={20}/></span><div><h3>{item.title}</h3><small>{new Date(item.date).toLocaleString('tr-TR')} · {formatTime(item.seconds)} · {(item.blob.size/1024).toFixed(0)} KB</small></div></div><audio ref={audio} src={url} controls loop={loop}/><div className="button-row"><label className="checkbox"><input type="checkbox" checked={loop} onChange={e=>setLoop(e.target.checked)}/> Tekrar dinle</label><button className="icon-btn" title="İndir" aria-label="Kaydı indir" onClick={()=>download(item.blob,`${item.id}.${item.mime.includes('mp4')?'m4a':item.mime.includes('ogg')?'ogg':'webm'}`)}><Download size={18}/></button><button className="icon-btn" title="Sil" aria-label="Kaydı sil" onClick={async()=>{if(confirm('Bu ses kaydı silinsin mi?')){await deleteRecording(item.id);onChange();}}}><Trash2 size={18}/></button></div><div className="marker-input"><input placeholder="Bu noktaya bir not bırak…" value={text} onChange={e=>setText(e.target.value)}/><button className="icon-btn" aria-label="İşaret ekle" disabled={!text.trim()} onClick={async()=>{await saveRecording({...item,markers:[...item.markers,{time:audio.current?.currentTime||0,text:text.trim()}]});setText('');onChange();}}><Flag size={18}/></button></div>{item.markers.map((m,i)=><button className="marker" key={i} onClick={()=>{if(audio.current){audio.current.currentTime=m.time;void audio.current.play();}}}>{formatTime(m.time)} · {m.text}</button>)}</article>;}
export function ArchivePage(){const [items,setItems]=useState<Recording[]>([]),[filter,setFilter]=useState(''),[error,setError]=useState('');const refresh=()=>allRecordings().then(setItems).catch(()=>setError('Kayıtlar okunamadı.'));useEffect(()=>{void refresh();},[]);const shown=items.filter(r=>`${r.title} ${r.exercise||''}`.toLocaleLowerCase('tr').includes(filter.toLocaleLowerCase('tr')));return <><div className="page-heading"><div><span className="eyebrow">SESİNİN YOLCULUĞU</span><h1>Kayıt arşivin.</h1><p>Dinle, fark et, yeniden dene. İki kaydı sırayla açarak karşılaştır.</p></div><span className="pill">{items.length} kayıt</span></div><input className="search-input" placeholder="Kayıt veya egzersiz ara…" aria-label="Kayıt ara" value={filter} onChange={e=>setFilter(e.target.value)}/>{error&&<p role="alert">{error}</p>}{shown.length?<div className="recordings-grid">{shown.map(r=><RecordingItem key={r.id} item={r} onChange={refresh}/>)}</div>:<Empty icon={<Mic/>} title="İlk kaydın için bir yer ayırdık.">Araçlar veya seans ekranında ses kaydı al. Kayıtların burada, cihazında kalır.</Empty>}</>;}
